language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.810
branches:
  only:
    - master
install:

script:
- dotnet build  Minio.Functional.Tests -c Release --framework netcoreapp2.1
- dotnet Minio.Functional.Tests/bin/Release/netcoreapp2.1/Minio.Functional.Tests.dll
